### ISSUE TITLE
Don't use hard coded dimensions.

### ISSUE THREAD

**Issue by KyleBastien** [JLaveta/AD340_Individual#1]
https://github.com/JLaveta/AD340_Individual/blob/7436cab908f45dcb311de2ffd76cb02006a0b94d/app/src/main/res/layout/activity_main.xml#L13

Throughout your layout file you're using hardcoded dimensions, don't do this. You should extract these to dimens.xml.

**Comment by JLaveta** [comment]
Fixed issue in branch for assignment 2. To be merged with master on completion of assignment 2.
